<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BlueVPN</AssemblyName>
    <RootNamespace>BlueVPN.Windows</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>bluevpn.ico</ApplicationIcon>
    <Version>5.9.8</Version>
    <AssemblyVersion>5.9.8.0</AssemblyVersion>
    <FileVersion>5.9.8.0</FileVersion>
    <InformationalVersion>5.9.8</InformationalVersion>
    <Platforms>AnyCPU</Platforms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <Compile Remove="SmokeConfigGenerator\**\*.cs" />
    <None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="runtime\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
