<?php
if (!defined('ABSPATH')) exit;

final class BlueVPN_Control_Center {
    private const TABS=[
        'overview'=>'نمای کلی','blueai'=>'BlueAI','database'=>'دیتابیس','panels'=>'PasarGuard','marzban'=>'Marzban','guardcore'=>'GuardCore','guardcore-manual'=>'صف GuardCore','plans'=>'پلن‌ها','bluepay'=>'BluePay','manual'=>'فعال‌سازی دستی','customers'=>'کاربران','orders'=>'پرداخت‌ها','app'=>'اپ و آپدیت','sms'=>'SMS / OTP'
    ];
    private const PAGE_SLUGS=[
        'overview'=>'bluevpn-manager',
        'blueai'=>'bluevpn-blueai',
        'database'=>'bluevpn-database',
        'panels'=>'bluevpn-pasarguard',
        'marzban'=>'bluevpn-marzban',
        'guardcore'=>'bluevpn-guardcore',
        'guardcore-manual'=>'bluevpn-guardcore-queue',
        'plans'=>'bluevpn-plans',
        'bluepay'=>'bluevpn-bluepay',
        'manual'=>'bluevpn-manual',
        'customers'=>'bluevpn-customers',
        'orders'=>'bluevpn-orders',
        'app'=>'bluevpn-app-update',
        'sms'=>'bluevpn-sms',
    ];
    public static function init(): void {
        foreach([
            'bluevpn_cc_save_provider'=>'save_provider','bluevpn_cc_toggle_provider'=>'toggle_provider','bluevpn_cc_test_provider'=>'test_provider',
            'bluevpn_cc_save_payment'=>'save_payment','bluevpn_cc_save_sms'=>'save_sms','bluevpn_cc_sync_customer'=>'sync_customer',
            'bluevpn_cc_manual_activate'=>'manual_activate','bluevpn_cc_attach_guardcore'=>'attach_guardcore','bluevpn_cc_export_backup'=>'export_backup',
            'bluevpn_cc_save_app_update_policy'=>'save_app_update_policy','bluevpn_cc_sync_app_release'=>'sync_app_release'
        ] as $hook=>$method)add_action('admin_post_'.$hook,[self::class,$method]);
    }
    private static function guard(): void { if(!current_user_can('manage_options'))wp_die('دسترسی ندارید.'); }
    private static function url(string $tab,array $args=[]): string { $slug=self::PAGE_SLUGS[$tab]??self::PAGE_SLUGS['overview'];return add_query_arg(array_merge(['page'=>$slug],$args),admin_url('admin.php')); }
    private static function redirect(string $tab,string $message,bool $error=false): void { $key=$error?'cc_error':'cc_msg';wp_safe_redirect(self::url($tab,[$key=>$message]));exit; }
    private static function esc($v): string { return esc_html((string)$v); }
    private static function fmt_bytes($v): string { $n=max(0,(float)$v);foreach(['B','KB','MB','GB','TB'] as $u){if($n<1024||$u==='TB')return number_format($n,$n<10&&$u!=='B'?2:0).' '.$u;$n/=1024;}return '0 B'; }
    private static function tab(): string {
        $t=sanitize_key((string)($_GET['tab']??'overview'));
        return isset(self::TABS[$t])?$t:'overview';
    }
    public static function page(): void { self::render_section('overview'); }
    public static function render_section(string $tab): void {
        self::guard();
        if(!isset(self::TABS[$tab]))$tab='overview';
        $title=self::TABS[$tab];
        BlueVPN_Unified_UI::shell_open($title);
        echo '<div class="wrap bvc-wrap" dir="rtl"><style>
        .bvc-wrap{max-width:1450px}.bvc-hero{background:linear-gradient(135deg,#071b38,#13284f);color:#fff;border-radius:18px;padding:22px;margin:16px 0;display:flex;justify-content:space-between;gap:16px;align-items:center}.bvc-hero h1{color:#fff;margin:0 0 5px}.bvc-hero small{color:#b9c9e6}.bvc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:13px}.bvc-card{background:#fff;border:1px solid #dcdcde;border-radius:14px;padding:16px;margin-bottom:14px}.bvc-card h2,.bvc-card h3{margin-top:0}.bvc-kpi strong{font-size:25px;display:block;margin-top:8px}.bvc-ok{color:#087c2c;font-weight:700}.bvc-bad{color:#b32d2e;font-weight:700}.bvc-warn{color:#9a6700;font-weight:700}.bvc-table{background:#fff;border-radius:12px;overflow:hidden}.bvc-table th,.bvc-table td{text-align:right;vertical-align:top}.bvc-table code{word-break:break-all}.bvc-actions{display:flex;gap:6px;flex-wrap:wrap}.bvc-form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.bvc-form-grid label{display:block;font-weight:650}.bvc-form-grid input,.bvc-form-grid select,.bvc-form-grid textarea{width:100%;margin-top:5px}.bvc-note{background:#f0f6fc;border-right:4px solid #2271b1;padding:12px;border-radius:8px;margin:10px 0}.bvc-code{direction:ltr;text-align:left;background:#f6f7f7;padding:8px;border-radius:7px;word-break:break-all}.bvc-badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef2f6}.bvc-danger{background:#fcf0f1;border-color:#d63638}.bvc-success{background:#edfaef;border-color:#00a32a}.bvc-section-home{display:inline-flex;align-items:center;gap:5px;color:#fff;text-decoration:none;margin-top:8px;font-weight:600}.bvc-section-home:hover{color:#dbeafe}@media(max-width:782px){.bvc-hero{display:block}.bvc-table{display:block;overflow:auto;white-space:nowrap}}
        </style>';
        echo '<div class="bvc-hero"><div><h1>'.self::esc($title).'</h1><small>BlueVPN Control Center • نسخه '.self::esc(BLUEVPN_MANAGER_VERSION).' • WordPress/MySQL</small>';
        if($tab!=='overview')echo '<div><a class="bvc-section-home" href="'.esc_url(self::url('overview')).'">← بازگشت به نمای کلی</a></div>';
        echo '</div><div><span class="bvc-badge">'.self::esc(BlueVPN_Utils::tehran_datetime_fa()).'</span></div></div>';
        if(isset($_GET['cc_msg']))echo '<div class="notice notice-success"><p>'.self::esc(sanitize_text_field(wp_unslash($_GET['cc_msg']))).'</p></div>';
        if(isset($_GET['cc_error']))echo '<div class="notice notice-error"><p>'.self::esc(sanitize_text_field(wp_unslash($_GET['cc_error']))).'</p></div>';
        $method='tab_'.str_replace('-','_',$tab);
        if(method_exists(self::class,$method))self::{$method}();
        echo '</div>';
        BlueVPN_Unified_UI::shell_close();
    }
    private static function count(string $table,string $where='1=1'): int { global $wpdb;$t=BlueVPN_DB::table($table);return (int)$wpdb->get_var("SELECT COUNT(*) FROM {$t} WHERE {$where}"); }
    private static function tab_overview(): void {
        global $wpdb;$stats=[
            ['کاربران',self::count('customers')],['اشتراک فعال',self::count('customers',"active=1 AND subscription_status='active'")],['پرداخت موفق',self::count('orders',"status IN ('paid','activated','paid_needs_sync','partial_needs_sync')")],['پلن فعال',self::count('plans','active=1 AND deleted=0')],['Provider فعال',self::count('pasarguard_panels','active=1')+self::count('marzban_panels','active=1')+self::count('guardcore_panels','active=1')],['اتصال زنده',self::count('ai_live_connections','connected=1 AND verified=1')]
        ];
        echo '<div class="bvc-grid">';foreach($stats as [$l,$v])echo '<div class="bvc-card bvc-kpi"><span>'.self::esc($l).'</span><strong>'.number_format($v).'</strong></div>';echo '</div>';
        $db=BlueVPN_DB::status();$cut=get_option('bluevpn_manager_cutover_ready','0')==='1';$app=get_option('bluevpn_manager_app_cutover_enabled','0')==='1';
        echo '<div class="bvc-grid"><div class="bvc-card"><h3>دیتابیس</h3><p class="'.($db['ready']?'bvc-ok':'bvc-bad').'">'.($db['ready']?'✅ MySQL آماده':'❌ نیاز به تعمیر').'</p><small>Schema '.self::esc($db['schema_version']).'</small></div><div class="bvc-card"><h3>مهاجرت</h3><p class="'.($cut?'bvc-ok':'bvc-warn').'">'.($cut?'✅ Verify نهایی انجام شده':'⏳ هنوز آماده نیست').'</p></div><div class="bvc-card"><h3>Backend اپ</h3><p class="'.($app?'bvc-ok':'bvc-warn').'">'.($app?'WordPress انتخاب شده':'هنوز Cutover اپ تأیید نشده').'</p><div class="bvc-code">'.self::esc(untrailingslashit(home_url('/'))).'</div></div></div>';
        $orders=$wpdb->get_results("SELECT order_code,status,amount_toman,created_at FROM ".BlueVPN_DB::table('orders')." ORDER BY created_at DESC LIMIT 8",ARRAY_A);
        echo '<div class="bvc-card"><h2>آخرین پرداخت‌ها</h2><table class="widefat striped bvc-table"><tr><th>سفارش</th><th>مبلغ</th><th>وضعیت</th><th>زمان</th></tr>';foreach($orders as $x)echo '<tr><td>'.self::esc($x['order_code']).'</td><td>'.number_format((int)$x['amount_toman']).'</td><td>'.self::esc($x['status']).'</td><td>'.self::esc($x['created_at']).'</td></tr>';echo '</table></div>';
    }
    private static function tab_blueai(): void {
        global $wpdb;$live=BlueVPN_DB::table('ai_live_connections');$agg=BlueVPN_DB::table('ai_route_aggregates');$events=BlueVPN_DB::table('ai_connection_events');$feedback=BlueVPN_DB::table('ai_feedback');
        echo '<div class="bvc-grid"><div class="bvc-card bvc-kpi"><span>اتصال زنده تأییدشده</span><strong>'.self::count('ai_live_connections','connected=1 AND verified=1').'</strong></div><div class="bvc-card bvc-kpi"><span>نمونه‌های اتصال</span><strong>'.number_format(self::count('ai_connection_events')).'</strong></div><div class="bvc-card bvc-kpi"><span>مسیرهای رتبه‌بندی‌شده</span><strong>'.number_format(self::count('ai_route_aggregates')).'</strong></div><div class="bvc-card bvc-kpi"><span>بازخورد</span><strong>'.number_format(self::count('ai_feedback')).'</strong></div></div>';
        $rows=$wpdb->get_results("SELECT location_title,operator,network_type,score,recent_score,sample_count,success_rate,average_ping_ms,updated_at FROM {$agg} ORDER BY recent_score DESC, sample_count DESC LIMIT 30",ARRAY_A);
        echo '<div class="bvc-card"><h2>بهترین مسیرها</h2><table class="widefat striped bvc-table"><tr><th>لوکیشن</th><th>اپراتور</th><th>شبکه</th><th>Score</th><th>نمونه</th><th>Success</th><th>Ping</th></tr>';foreach($rows as $x)echo '<tr><td>'.self::esc($x['location_title']).'</td><td>'.self::esc($x['operator']).'</td><td>'.self::esc($x['network_type']).'</td><td>'.self::esc($x['recent_score']).'</td><td>'.self::esc($x['sample_count']).'</td><td>'.number_format((float)$x['success_rate']*100,1).'%</td><td>'.number_format((float)$x['average_ping_ms'],0).' ms</td></tr>';echo '</table></div>';
        $l=$wpdb->get_results("SELECT customer_id,device_id,location_title,operator,network_type,ping_ms,health_score,last_seen_at FROM {$live} WHERE connected=1 ORDER BY last_seen_at DESC LIMIT 30",ARRAY_A);echo '<div class="bvc-card"><h2>اتصال‌های زنده</h2><table class="widefat striped bvc-table"><tr><th>کاربر</th><th>دستگاه</th><th>مسیر</th><th>اپراتور</th><th>Ping</th><th>Health</th><th>آخرین حضور</th></tr>';foreach($l as $x)echo '<tr><td>'.self::esc($x['customer_id']).'</td><td>'.self::esc($x['device_id']).'</td><td>'.self::esc($x['location_title']).'</td><td>'.self::esc($x['operator'].' / '.$x['network_type']).'</td><td>'.self::esc($x['ping_ms']).'</td><td>'.self::esc($x['health_score']).'</td><td>'.self::esc($x['last_seen_at']).'</td></tr>';echo '</table></div>';
    }
    private static function tab_database(): void {
        $s=BlueVPN_DB::status();$counts=BlueVPN_DB::counts();echo '<div class="bvc-grid"><div class="bvc-card"><h3>وضعیت</h3><p class="'.($s['ready']?'bvc-ok':'bvc-bad').'">'.($s['ready']?'✅ آماده':'❌ ناقص').'</p><small>MySQL '.self::esc($s['mysql_version']).'</small></div><div class="bvc-card"><h3>Schema</h3><strong>'.self::esc($s['schema_version']).'</strong></div><div class="bvc-card"><h3>Cutover</h3><strong>'.(get_option('bluevpn_manager_cutover_ready','0')==='1'?'آماده':'ناآماده').'</strong></div></div>';
        echo '<div class="bvc-card"><div class="bvc-actions"><a class="button" href="'.esc_url(admin_url('admin.php?page=bluevpn-migration')).'">ابزار مهاجرت</a><a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=bluevpn_cc_export_backup'),'bluevpn_cc_export_backup')).'">دانلود Backup JSON</a></div></div><table class="widefat striped bvc-table"><tr><th>جدول</th><th>تعداد</th></tr>';foreach($counts as $k=>$v)echo '<tr><td><code>'.self::esc($k).'</code></td><td>'.number_format((int)$v).'</td></tr>';echo '</table>';
    }
    private static function provider_tab(string $provider): void {
        global $wpdb;$maps=['pasarguard'=>['pasarguard_panels','PasarGuard'],'marzban'=>['marzban_panels','Marzban'],'guardcore'=>['guardcore_panels','GuardCore']];[$table,$title]=$maps[$provider];$t=BlueVPN_DB::table($table);$rows=$wpdb->get_results("SELECT * FROM {$t} ORDER BY id DESC",ARRAY_A);$edit=(int)($_GET['edit']??0);$current=$edit?$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE id=%d",$edit),ARRAY_A):[];
        echo '<div class="bvc-card"><h2>'.self::esc($title).' — افزودن / ویرایش</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('bluevpn_cc_save_provider');echo '<input type="hidden" name="action" value="bluevpn_cc_save_provider"><input type="hidden" name="provider" value="'.self::esc($provider).'"><input type="hidden" name="id" value="'.(int)$edit.'"><div class="bvc-form-grid">';
        self::input('name','نام',$current['name']??'',true);self::input('base_url','Base URL',$current['base_url']??'',true);
        if($provider==='pasarguard'){self::select('auth_mode','روش ورود',['api_key'=>'API Key','password'=>'Username / Password'],$current['auth_mode']??'api_key');self::input('api_key','API Key','',false,'password');self::input('username','نام کاربری','',false);self::input('password','رمز','',false,'password');self::textarea('proxy_settings_json','Proxy Settings JSON',$current['proxy_settings_json']??'{"vless":{}}');}
        elseif($provider==='marzban'){self::input('username','نام کاربری مدیر','',false);self::input('password','رمز مدیر','',false,'password');self::textarea('proxies_json','Proxies JSON',$current['proxies_json']??'{}');self::textarea('inbounds_json','Inbounds JSON',$current['inbounds_json']??'{}');}
        else{self::select('auth_mode','حالت',['manual'=>'Manual','api_key'=>'API Key','password'=>'Username / Password'],$current['auth_mode']??'manual');self::input('global_subscription_url','Global Subscription',$current['global_subscription_url']??'');self::input('api_key','API Key','',false,'password');self::input('username','نام کاربری','');self::input('password','رمز','',false,'password');self::select('usage_unit','واحد مصرف',['bytes'=>'Bytes','gb'=>'GB'],$current['usage_unit']??'bytes');self::select('expire_mode','نوع انقضا',['days'=>'Days','timestamp'=>'Timestamp'],$current['expire_mode']??'days');self::textarea('services_json','Services JSON',$current['services_json']??'[]');}
        echo '<label><input type="checkbox" name="verify_tls" value="1" '.checked(!isset($current['verify_tls'])||(int)($current['verify_tls']??1)===1,true,false).'> SSL Verify</label><label><input type="checkbox" name="active" value="1" '.checked(!isset($current['active'])||(int)($current['active']??1)===1,true,false).'> فعال</label></div>';submit_button($edit?'ذخیره تغییرات':'افزودن پنل','primary','submit',false);echo '</form></div>';
        echo '<table class="widefat striped bvc-table"><tr><th>ID</th><th>نام</th><th>URL</th><th>وضعیت</th><th>آخرین تست</th><th>عملیات</th></tr>';foreach($rows as $x){$test=wp_nonce_url(admin_url('admin-post.php?action=bluevpn_cc_test_provider&provider='.$provider.'&id='.(int)$x['id']),'bluevpn_cc_test_provider_'.$provider.'_'.$x['id']);$toggle=wp_nonce_url(admin_url('admin-post.php?action=bluevpn_cc_toggle_provider&provider='.$provider.'&id='.(int)$x['id']),'bluevpn_cc_toggle_provider_'.$provider.'_'.$x['id']);echo '<tr><td>'.(int)$x['id'].'</td><td>'.self::esc($x['name']).'</td><td><code>'.self::esc($x['base_url']).'</code></td><td>'.((int)$x['active']?'<span class="bvc-ok">فعال</span>':'<span class="bvc-bad">غیرفعال</span>').'</td><td>'.((int)$x['last_test_ok']?'<span class="bvc-ok">✅</span>':'<span class="bvc-bad">'.($x['last_test_at']?'❌':'—').'</span>').' '.self::esc($x['last_test_message']??'').'</td><td><div class="bvc-actions"><a class="button" href="'.esc_url(self::url($provider==='pasarguard'?'panels':$provider,['edit'=>(int)$x['id']])).'">ویرایش</a><a class="button" href="'.esc_url($test).'">تست</a><a class="button" href="'.esc_url($toggle).'">'.((int)$x['active']?'غیرفعال':'فعال').'‌کردن</a></div></td></tr>';}echo '</table>';
    }
    private static function input(string $name,string $label,$value='',bool $required=false,string $type='text'): void { echo '<label>'.self::esc($label).'<input type="'.$type.'" name="'.esc_attr($name).'" value="'.esc_attr((string)$value).'" '.($required?'required':'').'></label>'; }
    private static function textarea(string $name,string $label,$value=''): void { echo '<label>'.self::esc($label).'<textarea name="'.esc_attr($name).'" rows="4">'.self::esc($value).'</textarea></label>'; }
    private static function select(string $name,string $label,array $options,$value): void { echo '<label>'.self::esc($label).'<select name="'.esc_attr($name).'">';foreach($options as $k=>$v)echo '<option value="'.esc_attr($k).'" '.selected((string)$value,(string)$k,false).'>'.self::esc($v).'</option>';echo '</select></label>'; }
    private static function tab_panels(): void { self::provider_tab('pasarguard'); }
    private static function tab_marzban(): void { self::provider_tab('marzban'); }
    private static function tab_guardcore(): void { self::provider_tab('guardcore'); }
    private static function tab_guardcore_manual(): void {
        global $wpdb;$t=BlueVPN_DB::table('customers');$rows=$wpdb->get_results("SELECT id,email,phone,guardcore_username,guardcore_status,guardcore_subscription_url,guardcore_last_error FROM {$t} WHERE guardcore_status IN ('manual_pending','pending') OR (guardcore_panel_id IS NOT NULL AND guardcore_subscription_url='') ORDER BY id DESC LIMIT 100",ARRAY_A);
        echo '<div class="bvc-note">برای GuardCoreهای Manual، لینک اشتراک را اینجا ثبت کن؛ بعد وضعیت کاربر Active می‌شود.</div><table class="widefat striped bvc-table"><tr><th>کاربر</th><th>Username</th><th>وضعیت</th><th>لینک</th></tr>';foreach($rows as $x){echo '<tr><td>#'.(int)$x['id'].' '.self::esc($x['phone']?:$x['email']).'</td><td><code>'.self::esc($x['guardcore_username']).'</code></td><td>'.self::esc($x['guardcore_status']).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('bluevpn_cc_attach_guardcore_'.$x['id']);echo '<input type="hidden" name="action" value="bluevpn_cc_attach_guardcore"><input type="hidden" name="customer_id" value="'.(int)$x['id'].'"><input class="regular-text" name="subscription_url" value="'.esc_attr((string)$x['guardcore_subscription_url']).'"> <button class="button button-primary">ثبت</button></form></td></tr>';}echo '</table>';
    }
    private static function tab_plans(): void {
        global $wpdb;$p=BlueVPN_DB::table('plans');$pg=BlueVPN_DB::table('pasarguard_panels');$mz=BlueVPN_DB::table('marzban_panels');$gc=BlueVPN_DB::table('guardcore_panels');$rows=$wpdb->get_results("SELECT p.*,pg.name pg_name,mz.name mz_name,gc.name gc_name FROM {$p} p LEFT JOIN {$pg} pg ON pg.id=p.panel_id LEFT JOIN {$mz} mz ON mz.id=p.marzban_panel_id LEFT JOIN {$gc} gc ON gc.id=p.guardcore_panel_id WHERE p.deleted=0 ORDER BY p.sort_order,p.id",ARRAY_A);
        echo '<div class="bvc-actions" style="margin-bottom:12px"><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=bluevpn-plans')).'">افزودن / مدیریت پلن</a></div><table class="widefat striped bvc-table"><tr><th>ID</th><th>پلن</th><th>قیمت</th><th>مدت/حجم</th><th>Providerها</th><th>وضعیت</th></tr>';foreach($rows as $x){$prov=array_filter([$x['pg_name']?'PG: '.$x['pg_name']:'',$x['mz_name']?'MZ: '.$x['mz_name']:'',$x['gc_name']?'GC: '.$x['gc_name']:'']);echo '<tr><td>'.(int)$x['id'].'</td><td><strong>'.self::esc($x['title']).'</strong><br><small>'.self::esc($x['description']).'</small></td><td>'.number_format((int)$x['price_toman']).' تومان</td><td>'.(int)$x['duration_days'].' روز / '.(int)$x['data_limit_gb'].' GB</td><td>'.self::esc(implode(' | ',$prov)?:'—').'</td><td>'.((int)$x['active']?'<span class="bvc-ok">فعال</span>':'غیرفعال').'</td></tr>';}echo '</table>';
    }
    private static function tab_bluepay(): void {
        global $wpdb;$t=BlueVPN_DB::table('payment_settings');$s=$wpdb->get_row("SELECT * FROM {$t} WHERE id=1",ARRAY_A)?:[];$orders=BlueVPN_DB::table('orders');$pending=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$orders} WHERE status IN ('created','creating_invoice','pending','paid_needs_sync','partial_needs_sync')");
        echo '<div class="bvc-grid"><div class="bvc-card bvc-kpi"><span>سفارش‌های نیازمند پیگیری</span><strong>'.$pending.'</strong></div><div class="bvc-card"><h3>Callback</h3><div class="bvc-code">'.self::esc(home_url('/api/v1/webhooks/bluepay')).'</div></div></div><div class="bvc-card"><h2>تنظیمات BluePay</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('bluevpn_cc_save_payment');echo '<input type="hidden" name="action" value="bluevpn_cc_save_payment"><div class="bvc-form-grid">';self::input('base_url','Base URL',$s['base_url']??'https://bluepay-production.up.railway.app',true);self::input('api_key','API Key (خالی = حفظ فعلی)','',false,'password');self::input('callback_secret','Callback Secret (خالی = حفظ فعلی)','',false,'password');self::select('fee_mode','Fee Mode',['default'=>'Default','merchant'=>'Merchant','customer'=>'Customer','split'=>'Split'],$s['fee_mode']??'default');self::input('ttl_minutes','TTL دقیقه',$s['ttl_minutes']??30,true,'number');echo '<label><input type="checkbox" name="active" value="1" '.checked((int)($s['active']??0),1,false).'> فعال</label></div>';submit_button('ذخیره BluePay','primary','submit',false);echo '</form></div>';
    }
    private static function tab_manual(): void {
        global $wpdb;$ct=BlueVPN_DB::table('customers');$pt=BlueVPN_DB::table('plans');$customers=$wpdb->get_results("SELECT id,email,phone,subscription_status,plan_id FROM {$ct} ORDER BY id DESC LIMIT 200",ARRAY_A);$plans=$wpdb->get_results("SELECT id,title FROM {$pt} WHERE active=1 AND deleted=0 ORDER BY sort_order,id",ARRAY_A);
        echo '<div class="bvc-card"><h2>فعال‌سازی / تمدید دستی روی Providerها</h2><div class="bvc-note">این عملیات از تنظیمات همان پلن استفاده می‌کند و PasarGuard/Marzban را مستقیم Provision می‌کند. GuardCore Manual وارد صف می‌شود.</div><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('bluevpn_cc_manual_activate');echo '<input type="hidden" name="action" value="bluevpn_cc_manual_activate"><div class="bvc-form-grid"><label>کاربر<select name="customer_id" required><option value="">انتخاب…</option>';foreach($customers as $c)echo '<option value="'.(int)$c['id'].'">#'.(int)$c['id'].' '.self::esc($c['phone']?:$c['email']).' — '.self::esc($c['subscription_status']).'</option>';echo '</select></label><label>پلن<select name="plan_id" required><option value="">انتخاب…</option>';foreach($plans as $p)echo '<option value="'.(int)$p['id'].'">#'.(int)$p['id'].' '.self::esc($p['title']).'</option>';echo '</select></label></div>';submit_button('فعال‌سازی / تمدید','primary','submit',false);echo '</form></div>';
    }
    private static function tab_customers(): void {
        global $wpdb;$t=BlueVPN_DB::table('customers');$q=sanitize_text_field(wp_unslash($_GET['q']??''));$where='1=1';if($q!==''){$like='%'.$wpdb->esc_like($q).'%';$where=$wpdb->prepare('(email LIKE %s OR phone LIKE %s OR pg_username LIKE %s OR marzban_username LIKE %s)',$like,$like,$like,$like);} $rows=$wpdb->get_results("SELECT * FROM {$t} WHERE {$where} ORDER BY id DESC LIMIT 250",ARRAY_A);
        echo '<form method="get" class="bvc-card"><input type="hidden" name="page" value="bluevpn-manager"><input type="hidden" name="tab" value="customers"><input name="q" value="'.esc_attr($q).'" placeholder="ایمیل، موبایل، username"> <button class="button">جستجو</button></form><table class="widefat striped bvc-table"><tr><th>کاربر</th><th>اشتراک</th><th>مصرف</th><th>Provider</th><th>آخرین Sync</th><th>عملیات</th></tr>';foreach($rows as $x){$sync=wp_nonce_url(admin_url('admin-post.php?action=bluevpn_cc_sync_customer&customer_id='.(int)$x['id']),'bluevpn_cc_sync_customer_'.$x['id']);echo '<tr><td>#'.(int)$x['id'].'<br>'.self::esc($x['phone']?:$x['email']).'</td><td>'.self::esc($x['subscription_status']).'<br><small>'.self::esc($x['subscription_expire']).'</small></td><td>'.self::fmt_bytes($x['used_traffic_bytes']).' / '.self::fmt_bytes($x['data_limit_bytes']).'</td><td><small>PG '.self::esc($x['pg_username']).'<br>MZ '.self::esc($x['marzban_username']).'<br>GC '.self::esc($x['guardcore_status']).'</small></td><td>'.self::esc($x['last_sync_at']).'<br><small class="bvc-bad">'.self::esc($x['last_sync_error']).'</small></td><td><div class="bvc-actions"><a class="button" href="'.esc_url($sync).'">Sync</a><a class="button" href="'.esc_url(admin_url('admin.php?page=bluevpn-customers')).'">فعال/غیرفعال</a></div></td></tr>';}echo '</table>';
    }
    private static function tab_orders(): void {
        global $wpdb;$o=BlueVPN_DB::table('orders');$c=BlueVPN_DB::table('customers');$p=BlueVPN_DB::table('plans');$rows=$wpdb->get_results("SELECT o.*,c.email,c.phone,p.title plan_title FROM {$o} o LEFT JOIN {$c} c ON c.id=o.customer_id LEFT JOIN {$p} p ON p.id=o.plan_id ORDER BY o.created_at DESC LIMIT 250",ARRAY_A);
        echo '<table class="widefat striped bvc-table"><tr><th>سفارش</th><th>کاربر</th><th>پلن</th><th>مبلغ</th><th>وضعیت</th><th>پرداخت</th><th>خطا</th><th>زمان</th></tr>';foreach($rows as $x)echo '<tr><td><code>'.self::esc($x['order_code']).'</code></td><td>'.self::esc($x['phone']?:$x['email']).'</td><td>'.self::esc($x['plan_title']).'</td><td>'.number_format((int)$x['amount_toman']).'</td><td>'.self::esc($x['status']).'</td><td><code>'.self::esc($x['payment_id']).'</code></td><td><small class="bvc-bad">'.self::esc($x['activation_error']).'</small></td><td>'.self::esc($x['created_at']).'</td></tr>';echo '</table>';
    }
    private static function tab_app(): void {
        $s=BlueVPN_DB::settings();
        $cfg=BlueVPN_App_Release_Manager::settings();
        $status=BlueVPN_App_Release_Manager::status();
        $last=BlueVPN_App_Release_Manager::last_sync();
        $assets=is_array($s['apk_assets']??null)?$s['apk_assets']:[];
        $meta=is_array($s['apk_asset_meta']??null)?$s['apk_asset_meta']:[];
        $published=(string)($s['release_published_at']??'');
        $publishedMysql=BlueVPN_Utils::mysql_from_iso($published);
        $statusClass=in_array((string)($status['status']??''),['synced','up_to_date'],true)?'bvc-ok':(((string)($status['status']??'')==='never')?'bvc-warn':'bvc-bad');
        echo '<div class="bvc-grid">';
        echo '<div class="bvc-card bvc-kpi"><span>آخرین نسخه اپ</span><strong>'.self::esc($s['latest_version']).'</strong><small>Version Code '.(int)$s['latest_version_code'].'</small></div>';
        echo '<div class="bvc-card bvc-kpi"><span>Build</span><strong>#'.(int)($s['release_build_number']??0).'</strong><small>Commit '.self::esc(substr((string)($s['release_commit']??''),0,12)?:'—').'</small></div>';
        echo '<div class="bvc-card"><h3>همگام‌سازی GitHub</h3><p class="'.esc_attr($statusClass).'">'.self::esc((string)($status['message']??'در انتظار اولین همگام‌سازی')).'</p><small>'.($last?'آخرین بررسی: '.self::esc(wp_date('Y-m-d H:i:s',$last)):'هنوز اجرا نشده').'</small></div>';
        echo '<div class="bvc-card"><h3>انتشار</h3><p>'.($publishedMysql?self::esc(BlueVPN_Utils::tehran_datetime_fa($publishedMysql)):'—').'</p>'.(!empty($s['release_url'])?'<a class="button" target="_blank" rel="noopener" href="'.esc_url($s['release_url']).'">مشاهده Release</a>':'').'</div>';
        echo '</div>';

        echo '<div class="bvc-card"><h2>APKهای نسخه جاری</h2>';
        if(!$assets){echo '<p class="bvc-warn">هنوز APK از GitHub به WordPress همگام نشده است.</p>';}
        else{
            echo '<table class="widefat striped bvc-table"><tr><th>معماری</th><th>فایل</th><th>حجم</th><th>SHA-256</th><th>دانلود</th></tr>';
            foreach($assets as $abi=>$url){$m=is_array($meta[$abi]??null)?$meta[$abi]:[];echo '<tr><td><strong>'.self::esc($abi).'</strong></td><td>'.self::esc($m['filename']??'').'</td><td>'.self::fmt_bytes((int)($m['size']??0)).'</td><td><code>'.self::esc($m['sha256']??'—').'</code></td><td><a class="button" target="_blank" rel="noopener" href="'.esc_url($url).'">APK</a></td></tr>';}
            echo '</table>';
        }
        echo '</div>';

        echo '<div class="bvc-card"><h2>سیاست بروزرسانی اپ</h2><p>GitHub فقط APK را Build و Release می‌کند؛ WordPress نسخه، لینک معماری مناسب و سیاست اجباری/اختیاری را به اپ اعلام می‌کند.</p>';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('bluevpn_cc_save_app_update_policy');echo '<input type="hidden" name="action" value="bluevpn_cc_save_app_update_policy"><div class="bvc-form-grid">';
        self::input('owner','GitHub Owner',$cfg['owner']??'hazhanhasani');
        self::input('repo','Repository',$cfg['repo']??'bluevpnapp');
        self::input('minimum_version','حداقل نسخه مجاز',$s['minimum_version']??'0.0.0');
        self::input('support_url','لینک پشتیبانی',$s['support_url']??'');
        self::input('title_override','عنوان ثابت آپدیت (اختیاری)',$cfg['title_override']??'');
        echo '<label style="grid-column:1/-1">متن ثابت آپدیت (اختیاری)<textarea name="message_override" rows="3">'.esc_textarea((string)($cfg['message_override']??'')).'</textarea></label>';
        echo '<label><input type="checkbox" name="app_auto_sync" value="1" '.checked(!empty($cfg['auto_sync']),true,false).'> تشخیص خودکار Release جدید GitHub</label>';
        echo '<label><input type="checkbox" name="auto_update" value="1" '.checked(!empty($s['auto_update']),true,false).'> دانلود خودکار APK جدید داخل اپ</label>';
        echo '<label><input type="checkbox" name="force_update" value="1" '.checked(!empty($s['force_update']),true,false).'> بروزرسانی اجباری</label>';
        echo '<label><input type="checkbox" name="maintenance" value="1" '.checked(!empty($s['maintenance']),true,false).'> حالت تعمیرات</label>';
        echo '</div>';submit_button('ذخیره سیاست بروزرسانی','primary','submit',false);echo '</form></div>';

        echo '<div class="bvc-card"><h2>اتوماسیون</h2><div class="bvc-grid"><div><strong>① Build</strong><p>GitHub Actions نسخه و APKهای امضاشده را می‌سازد.</p></div><div><strong>② Sync</strong><p>WordPress Release جدید را خودکار تشخیص می‌دهد.</p></div><div><strong>③ App</strong><p>اپ از <code>/api/v1/mobile/config</code> نسخه و APK مناسب دستگاه را دریافت می‌کند.</p></div></div>';
        echo '<p><strong>API بروزرسانی:</strong></p><div class="bvc-code">'.self::esc(untrailingslashit(home_url('/')).'/api/v1/mobile/config').'</div>';
        echo '<div class="bvc-actions" style="margin-top:12px"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('bluevpn_cc_sync_app_release');echo '<input type="hidden" name="action" value="bluevpn_cc_sync_app_release">';submit_button('همگام‌سازی همین حالا','secondary','submit',false);echo '</form><a class="button" href="'.esc_url(admin_url('admin.php?page=bluevpn-app-connection')).'">تست اتصال اپ</a><a class="button" href="'.esc_url(admin_url('admin.php?page=bluevpn-github-updater')).'">آپدیت خود افزونه</a></div></div>';
    }

    private static function tab_sms(): void {
        global $wpdb;$t=BlueVPN_DB::table('sms_settings');$s=$wpdb->get_row("SELECT * FROM {$t} WHERE id=1",ARRAY_A)?:[];$d=BlueVPN_DB::table('sms_deliveries');$recent=$wpdb->get_results("SELECT event_key,phone,status,attempts,last_error,created_at FROM {$d} ORDER BY created_at DESC LIMIT 50",ARRAY_A);
        echo '<div class="bvc-card"><h2>SMS / OTP</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('bluevpn_cc_save_sms');echo '<input type="hidden" name="action" value="bluevpn_cc_save_sms"><div class="bvc-form-grid">';self::input('provider','Provider',$s['provider']??'iranpayamak');self::input('base_url','Base URL',$s['base_url']??'');self::input('api_key','API Key (خالی = حفظ)','',false,'password');self::input('from_number','شماره ارسال',$s['from_number']??'');self::input('pattern_code','Pattern',$s['pattern_code']??'');self::input('parameter_name','نام پارامتر',$s['parameter_name']??'code');echo '<label>طول OTP<input type="number" value="6" readonly disabled><small style="display:block;margin-top:5px">ورود BlueVPN همیشه ۶ رقمی است.</small></label>';echo '<input type="hidden" name="otp_length" value="6">';self::input('otp_ttl_seconds','TTL ثانیه',$s['otp_ttl_seconds']??120,true,'number');self::input('resend_seconds','ارسال مجدد بعد از (ثانیه)',$s['resend_seconds']??60,true,'number');echo '<label><input type="checkbox" name="active" value="1" '.checked((int)($s['active']??0),1,false).'> OTP فعال</label><label><input type="checkbox" name="notification_active" value="1" '.checked((int)($s['notification_active']??0),1,false).'> اعلان‌ها فعال</label></div>';submit_button('ذخیره SMS','primary','submit',false);echo '</form></div><table class="widefat striped bvc-table"><tr><th>رویداد</th><th>موبایل</th><th>وضعیت</th><th>تلاش</th><th>خطا</th><th>زمان</th></tr>';foreach($recent as $x)echo '<tr><td>'.self::esc($x['event_key']).'</td><td>'.self::esc($x['phone']).'</td><td>'.self::esc($x['status']).'</td><td>'.self::esc($x['attempts']).'</td><td>'.self::esc($x['last_error']).'</td><td>'.self::esc($x['created_at']).'</td></tr>';echo '</table>';
    }
    public static function save_provider(): void {
        self::guard();check_admin_referer('bluevpn_cc_save_provider');global $wpdb;$provider=sanitize_key((string)($_POST['provider']??''));$maps=['pasarguard'=>'pasarguard_panels','marzban'=>'marzban_panels','guardcore'=>'guardcore_panels'];if(!isset($maps[$provider]))self::redirect('overview','Provider نامعتبر است.',true);$id=(int)($_POST['id']??0);$t=BlueVPN_DB::table($maps[$provider]);$old=$id?$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE id=%d",$id),ARRAY_A):[];$data=['name'=>sanitize_text_field(wp_unslash($_POST['name']??'')),'base_url'=>untrailingslashit(esc_url_raw(wp_unslash($_POST['base_url']??''))),'verify_tls'=>isset($_POST['verify_tls'])?1:0,'active'=>isset($_POST['active'])?1:0];
        $secret=function(string $post,string $col)use($old){$v=trim((string)wp_unslash($_POST[$post]??''));return $v!==''?BlueVPN_Utils::encrypt_secret($v):(string)($old[$col]??'');};
        if($provider==='pasarguard'){$data+=['auth_mode'=>sanitize_key((string)($_POST['auth_mode']??'api_key')),'api_key_enc'=>$secret('api_key','api_key_enc'),'username_enc'=>$secret('username','username_enc'),'password_enc'=>$secret('password','password_enc'),'proxy_settings_json'=>self::sanitize_json($_POST['proxy_settings_json']??'{}','{}')];}
        elseif($provider==='marzban'){$data+=['username_enc'=>$secret('username','username_enc'),'password_enc'=>$secret('password','password_enc'),'proxies_json'=>self::sanitize_json($_POST['proxies_json']??'{}','{}'),'inbounds_json'=>self::sanitize_json($_POST['inbounds_json']??'{}','{}')];}
        else{$data+=['global_subscription_url'=>esc_url_raw(wp_unslash($_POST['global_subscription_url']??'')),'auth_mode'=>sanitize_key((string)($_POST['auth_mode']??'manual')),'api_key_enc'=>$secret('api_key','api_key_enc'),'username_enc'=>$secret('username','username_enc'),'password_enc'=>$secret('password','password_enc'),'usage_unit'=>sanitize_key((string)($_POST['usage_unit']??'bytes')),'expire_mode'=>sanitize_key((string)($_POST['expire_mode']??'days')),'services_json'=>self::sanitize_json($_POST['services_json']??'[]','[]')];}
        if($id)$ok=$wpdb->update($t,$data,['id'=>$id]);else{$data['created_at']=BlueVPN_Utils::now_mysql();$ok=$wpdb->insert($t,$data);}self::redirect($provider==='pasarguard'?'panels':$provider,$ok===false?'ذخیره پنل ناموفق بود.':'پنل ذخیره شد.',$ok===false);
    }
    private static function sanitize_json($value,string $fallback): string { $raw=trim((string)wp_unslash($value));$d=json_decode($raw,true);return is_array($d)?wp_json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):$fallback; }
    public static function toggle_provider(): void { self::guard();global $wpdb;$p=sanitize_key((string)($_GET['provider']??''));$id=(int)($_GET['id']??0);check_admin_referer('bluevpn_cc_toggle_provider_'.$p.'_'.$id);$map=['pasarguard'=>'pasarguard_panels','marzban'=>'marzban_panels','guardcore'=>'guardcore_panels'];if(!isset($map[$p]))self::redirect('overview','Provider نامعتبر.',true);$t=BlueVPN_DB::table($map[$p]);$v=(int)$wpdb->get_var($wpdb->prepare("SELECT active FROM {$t} WHERE id=%d",$id));$wpdb->update($t,['active'=>$v?0:1],['id'=>$id]);self::redirect($p==='pasarguard'?'panels':$p,'وضعیت Provider تغییر کرد.'); }
    public static function test_provider(): void { self::guard();$p=sanitize_key((string)($_GET['provider']??''));$id=(int)($_GET['id']??0);check_admin_referer('bluevpn_cc_test_provider_'.$p.'_'.$id);$r=BlueVPN_Providers::test($p,$id);self::redirect($p==='pasarguard'?'panels':$p,$r['message'],!$r['ok']); }
    public static function save_payment(): void { self::guard();check_admin_referer('bluevpn_cc_save_payment');global $wpdb;$t=BlueVPN_DB::table('payment_settings');$old=$wpdb->get_row("SELECT * FROM {$t} WHERE id=1",ARRAY_A)?:[];$api=trim((string)wp_unslash($_POST['api_key']??''));$cb=trim((string)wp_unslash($_POST['callback_secret']??''));$wpdb->replace($t,['id'=>1,'base_url'=>untrailingslashit(esc_url_raw(wp_unslash($_POST['base_url']??''))),'api_key_enc'=>$api!==''?BlueVPN_Utils::encrypt_secret($api):(string)($old['api_key_enc']??''),'callback_secret_enc'=>$cb!==''?BlueVPN_Utils::encrypt_secret($cb):(string)($old['callback_secret_enc']??''),'fee_mode'=>sanitize_key((string)($_POST['fee_mode']??'default')),'ttl_minutes'=>max(5,min(60,(int)($_POST['ttl_minutes']??30))),'active'=>isset($_POST['active'])?1:0,'updated_at'=>BlueVPN_Utils::now_mysql()]);self::redirect('bluepay','تنظیمات BluePay ذخیره شد.'); }
    public static function save_sms(): void { self::guard();check_admin_referer('bluevpn_cc_save_sms');global $wpdb;$t=BlueVPN_DB::table('sms_settings');$old=$wpdb->get_row("SELECT * FROM {$t} WHERE id=1",ARRAY_A)?:[];$api=trim((string)wp_unslash($_POST['api_key']??''));$data=$old;$data['id']=1;$data['provider']=sanitize_key((string)($_POST['provider']??'iranpayamak'));$data['base_url']=esc_url_raw(wp_unslash($_POST['base_url']??''));$data['api_key_enc']=$api!==''?BlueVPN_Utils::encrypt_secret($api):(string)($old['api_key_enc']??'');$data['from_number']=sanitize_text_field(wp_unslash($_POST['from_number']??''));$data['pattern_code']=sanitize_text_field(wp_unslash($_POST['pattern_code']??''));$data['parameter_name']=sanitize_key((string)($_POST['parameter_name']??'code'));$data['otp_length']=6;$data['otp_ttl_seconds']=max(60,min(600,(int)($_POST['otp_ttl_seconds']??120)));$data['resend_seconds']=max(30,min(600,(int)($_POST['resend_seconds']??60)));$data['active']=isset($_POST['active'])?1:0;$data['notification_active']=isset($_POST['notification_active'])?1:0;$data['updated_at']=BlueVPN_Utils::now_mysql();$wpdb->replace($t,$data);self::redirect('sms','تنظیمات SMS ذخیره شد.'); }
    public static function sync_customer(): void { self::guard();$id=(int)($_GET['customer_id']??0);check_admin_referer('bluevpn_cc_sync_customer_'.$id);$r=BlueVPN_Providers::sync_customer($id);self::redirect('customers',$r['message'],!$r['ok']); }
    public static function manual_activate(): void { self::guard();check_admin_referer('bluevpn_cc_manual_activate');$r=BlueVPN_Providers::provision_customer((int)($_POST['customer_id']??0),(int)($_POST['plan_id']??0));self::redirect('manual',$r['message'],!$r['ok']&&!($r['partial']??false)); }
    public static function attach_guardcore(): void { self::guard();$id=(int)($_POST['customer_id']??0);check_admin_referer('bluevpn_cc_attach_guardcore_'.$id);$r=BlueVPN_Providers::attach_guardcore($id,(string)wp_unslash($_POST['subscription_url']??''));self::redirect('guardcore-manual',$r['message'],!$r['ok']); }
    public static function save_app_update_policy(): void {
        self::guard();check_admin_referer('bluevpn_cc_save_app_update_policy');
        $owner=sanitize_text_field(wp_unslash($_POST['owner']??''));$repo=sanitize_text_field(wp_unslash($_POST['repo']??''));
        BlueVPN_App_Release_Manager::save_settings(['owner'=>$owner,'repo'=>$repo,'auto_sync'=>isset($_POST['app_auto_sync']),'title_override'=>sanitize_text_field(wp_unslash($_POST['title_override']??'')),'message_override'=>sanitize_textarea_field(wp_unslash($_POST['message_override']??''))]);
        $s=BlueVPN_DB::settings();
        $min=sanitize_text_field(wp_unslash($_POST['minimum_version']??'0.0.0'));if(!preg_match('/^\d+\.\d+\.\d+$/',$min))$min='0.0.0';
        $s['minimum_version']=$min;$s['support_url']=esc_url_raw(wp_unslash($_POST['support_url']??''));$s['auto_update']=isset($_POST['auto_update']);$s['force_update']=isset($_POST['force_update']);$s['maintenance']=isset($_POST['maintenance']);
        BlueVPN_DB::save_settings($s);BlueVPN_App_Release_Manager::ensure_schedule();
        self::redirect('app','سیاست بروزرسانی اپ ذخیره شد.');
    }
    public static function sync_app_release(): void {
        self::guard();check_admin_referer('bluevpn_cc_sync_app_release');
        $r=BlueVPN_App_Release_Manager::sync_now(true,'wordpress_admin');
        self::redirect('app',(string)($r['message']??'همگام‌سازی انجام شد.'),empty($r['ok']));
    }
    public static function export_backup(): void { self::guard();check_admin_referer('bluevpn_cc_export_backup');global $wpdb;nocache_headers();header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="bluevpn-wordpress-backup-'.gmdate('Ymd-His').'.json"');echo '{"meta":'.wp_json_encode(['version'=>BLUEVPN_MANAGER_VERSION,'exported_at'=>BlueVPN_Utils::iso_now(),'site'=>home_url('/')]).',"tables":{';$first=true;foreach(BlueVPN_DB::table_names() as $name){if(!$first)echo ',';$first=false;echo wp_json_encode($name).':';$rows=$wpdb->get_results('SELECT * FROM '.BlueVPN_DB::table($name),ARRAY_A);echo wp_json_encode($rows,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}echo '}}';exit; }
}
