<?php if (class_exists('BlueVPN_Elementor_Integration') && BlueVPN_Elementor_Integration::page_ready()) { get_header(); while (have_posts()) { the_post(); the_content(); } get_footer(); return; } ?>
<?php get_header(); $cfg=bluevpn_site_mobile_config(); $apk=(string)($cfg['apk_url']??''); $latest=(string)($cfg['latest_version']??'—'); ?>
<section class="bv-subhero bv-download-hero">
  <div class="bv-shell bv-subhero-grid">
    <div data-bv-reveal><span class="bv-kicker bv-kicker-light">BLUEVPN FOR ANDROID</span><h1>آخرین نسخه، مستقیم و آماده نصب.</h1><p>همیشه آخرین نسخه BlueVPN را از همین صفحه دریافت کن؛ ساده، مستقیم و بدون سردرگمی.</p><div class="bv-download-meta"><span><i></i> نسخه <?php echo esc_html($latest); ?></span><span>Android</span></div><div class="bv-subhero-actions"><?php if ($apk && wp_http_validate_url($apk)): ?><a class="bv-btn bv-btn-light bv-btn-xl" href="<?php echo esc_url($apk); ?>" rel="nofollow">دانلود APK <span>↓</span></a><?php else: ?><span class="bv-btn bv-btn-disabled bv-btn-xl">لینک دانلود هنوز منتشر نشده</span><?php endif; ?></div></div>
    <div class="bv-download-device" data-bv-reveal aria-hidden="true"><div class="bv-device-top"><span></span><i></i></div><div class="bv-device-logo">B</div><b>BlueVPN</b><small>v<?php echo esc_html($latest); ?></small><div class="bv-device-button">Download</div><div class="bv-device-progress"><i></i></div></div>
  </div>
</section>
<section class="bv-section bv-download-info-section"><div class="bv-shell"><div class="bv-download-panel" data-bv-reveal><div><span class="bv-kicker">انتشار فعلی</span><h2>BlueVPN for Android</h2><p>نسخه <b><?php echo esc_html($latest); ?></b> آماده دانلود است.</p></div><div class="bv-download-facts"><div><span>سیستم‌عامل</span><b>Android</b></div><div><span>فرمت</span><b>APK</b></div><div><span>وضعیت</span><b>آخرین نسخه</b></div></div></div><div class="bv-install-steps"><article data-bv-reveal><span>01</span><h3>دانلود</h3><p>فایل APK آخرین انتشار را دریافت کن.</p></article><article data-bv-reveal><span>02</span><h3>نصب</h3><p>در صورت نیاز اجازه نصب از منبع موردنظر را تأیید کن.</p></article><article data-bv-reveal><span>03</span><h3>ورود و اتصال</h3><p>وارد حساب شو، لوکیشن را انتخاب کن و اتصال را شروع کن.</p></article></div></div></section>
<?php get_footer(); ?>
