from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def read(p): return (ROOT/p).read_text(encoding="utf-8")
def req(ok,msg):
    if not ok: raise SystemExit("FAIL: "+msg)
account=read("android-source/BlueVpnAccountManager.kt")
home=read("android-source/BlueVpnHomeActivity.kt")
ent=read("android-source/BlueVpnEntitlement.kt")
auth=read("bluevpn-manager/includes/class-bluevpn-auth.php")
api=read("bluevpn-manager/includes/class-bluevpn-api.php")
providers=read("bluevpn-manager/includes/class-bluevpn-providers.php")
req("autoUpdate = true" not in account,"managed subscriptions must not use upstream auto-update")
pool_block=account[account.index("fun preferredServerGuids"):account.index("fun entitlementPoolFingerprint")]
req("val exact = usableServerGuids(entitlementSubscriptionGuids(c))" in pool_block,"premium must prefer exact current subscription")
req("if (exact.isNotEmpty() || !active(c)) return exact" in pool_block,"Free mode must remain strict while Premium can use LKG")
req("val freeServerGuids = allFreeServerGuids()" in pool_block and "it !in freeServerGuids" in pool_block,"Premium LKG must exclude known Free servers")
req("decodeAllServerList()" in pool_block,"Premium compatibility fallback must survive transient v2rayNG imports")
req('if (force) "/api/v1/account/sync" else "/api/v1/account"' in account,"routine account refresh must use WordPress snapshot")
req("lastForegroundAccountSyncAt > 120_000L" in home,"foreground sync must be throttled")
req("syncManagedAccount(force = false)" in home,"resume sync must be non-forced")
req("preserveLastGoodPremium" in account and "provider_fail_open" in auth,"transient provider errors must not drop Premium to Free")
req("BlueVPN_Providers::sync_customer((int)$c['id']);" not in api,"GET /account must not poll providers")
req("wordpress_snapshot" in api,"account API must identify snapshot source")
req("request_background_sync" in api and "mode'=>'background" in api,"app account sync must queue provider polling instead of blocking UI")
req("preserved_status" in providers,"provider sync must fail open")
req("bluevpn_refresh_subscription_snapshot" in providers and "stale-while-revalidate" in providers,"subscription snapshot cache must exist")
req("profile-update-interval: 24" in providers,"subscription auto refresh interval must be controlled")
req("guest'=>(int)$c['id']===0" in api,"guest BlueAI events must be supported")
req("public static function ai_recommendations" in api and "BlueVPN_Auth::current_customer($r); $s=BlueVPN_DB::settings()" not in api[api.index("public static function ai_recommendations"):api.index("public static function ai_dashboard")],"AI recommendations must be readable in Free mode")
req("dashboard_device" in read("bluevpn-manager/includes/class-bluevpn-ai.php") and "request(c, \"GET\", \"/api/v1/ai/dashboard\", null, false)" in account,"guest BlueAI dashboard must work")
print("OK: BlueVPN 4.0.27 WordPress connectivity hotfix validated")
